mydbt_fundamentals:
  outputs:
    dev:
      type: snowflake
      account: ueoeiod-yg90860
      user: dbt

      role: TRANSFORM
      private_key: "---
      private_key_passphrase: q

      database: analytics
      schema: dbt_singh
      threads: 1
      warehouse: transforming
  target: dev

